import type { TabEvent } from "./TabNotation";

export type Difficulty = "Easy" | "Medium" | "Hard";

export type Phrase = {
  id: string;
  title: string;
  difficulty: Difficulty;
  bars: number;
  memo: string;
  totalSteps: number;
  tabEvents: TabEvent[];
};

export const phrases: Phrase[] = [
  {
    id: "minor-pentatonic-up",
    title: "Minor Pentatonic Up",
    difficulty: "Easy",
    bars: 1,
    memo: "Minor pentatonic ascending line",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 5, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 4, duration: "eighth", notes: [{ string: 4, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 8, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 10, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 12, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 14, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
    ],
  },
  {
    id: "minor-pentatonic-down",
    title: "Minor Pentatonic Down",
    difficulty: "Easy",
    bars: 1,
    memo: "Descending line for return practice",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 2, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 6, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 10, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 12, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 14, duration: "eighth", notes: [{ string: 4, fret: "5" }] },
    ],
  },
  {
    id: "low-string-riff",
    title: "Low String Riff",
    difficulty: "Medium",
    bars: 2,
    memo: "Muted eighth-note rock pattern",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 5, fret: "7" }, { string: 6, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 5, fret: "7" }, { string: 6, fret: "5" }] },
      { step: 4, duration: "quarter", notes: [{ string: 5, fret: "5" }, { string: 6, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 5, fret: "7" }, { string: 6, fret: "5" }] },
      { step: 10, duration: "eighth", notes: [{ string: 5, fret: "7" }, { string: 6, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 5, fret: "5" }, { string: 6, fret: "5" }] },
      { step: 16, duration: "eighth", notes: [{ string: 5, fret: "7" }, { string: 6, fret: "5" }] },
      { step: 18, duration: "eighth", notes: [{ string: 5, fret: "7" }, { string: 6, fret: "5" }] },
      { step: 20, duration: "eighth", notes: [{ string: 5, fret: "5" }, { string: 6, fret: "5" }] },
      { step: 24, duration: "eighth", notes: [{ string: 5, fret: "8" }, { string: 6, fret: "5" }] },
      { step: 26, duration: "eighth", notes: [{ string: 5, fret: "7" }, { string: 6, fret: "5" }] },
      { step: 28, duration: "quarter", notes: [{ string: 5, fret: "5" }, { string: 6, fret: "5" }] },
    ],
  },
  {
    id: "blues-box",
    title: "Blues Box",
    difficulty: "Medium",
    bars: 1,
    memo: "Small box phrase without bending",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 4, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 8, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
      { step: 12, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 14, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
    ],
  },
  {
    id: "rest-practice",
    title: "Rest Practice",
    difficulty: "Medium",
    bars: 1,
    memo: "Short rests inside an eighth-note line",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "quarter", notes: [{ string: 4, fret: "7" }] },
      { step: 4, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 8, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 10, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 12, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 14, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
    ],
  },
  {
    id: "two-bar-run",
    title: "Two Bar Run",
    difficulty: "Medium",
    bars: 2,
    memo: "Connect low and high positions",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 5, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 4, duration: "eighth", notes: [{ string: 5, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 8, duration: "eighth", notes: [{ string: 4, fret: "5" }] },
      { step: 10, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 12, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 14, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 16, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 18, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 20, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 22, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 24, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 26, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 28, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
    ],
  },
  {
    id: "call-response",
    title: "Call Response",
    difficulty: "Medium",
    bars: 2,
    memo: "Two short answers with space between them",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 4, duration: "quarter", notes: [{ string: 2, fret: "5" }] },
      { step: 12, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 14, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 16, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 18, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 20, duration: "quarter", notes: [{ string: 4, fret: "7" }] },
      { step: 28, duration: "quarter", notes: [{ string: 5, fret: "5" }] },
    ],
  },
  {
    id: "double-stop-stab",
    title: "Double Stop Stab",
    difficulty: "Medium",
    bars: 1,
    memo: "Two-string accents on the upper strings",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "quarter", notes: [{ string: 1, fret: "5" }, { string: 2, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 1, fret: "8" }, { string: 2, fret: "8" }] },
      { step: 6, duration: "eighth", notes: [{ string: 1, fret: "5" }, { string: 2, fret: "5" }] },
      { step: 8, duration: "quarter", notes: [{ string: 2, fret: "8" }, { string: 3, fret: "7" }] },
      { step: 12, duration: "quarter", notes: [{ string: 2, fret: "5" }, { string: 3, fret: "5" }] },
    ],
  },
  {
    id: "syncopated-push",
    title: "Syncopated Push",
    difficulty: "Hard",
    bars: 1,
    memo: "Off-beat accents for tighter time feel",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 3, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 9, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 12, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 14, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
    ],
  },
  {
    id: "octave-anchor",
    title: "Octave Anchor",
    difficulty: "Medium",
    bars: 1,
    memo: "Root and octave targets across the box",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "quarter", notes: [{ string: 6, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 6, duration: "eighth", notes: [{ string: 4, fret: "5" }] },
      { step: 8, duration: "quarter", notes: [{ string: 4, fret: "7" }] },
      { step: 12, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 14, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
    ],
  },
  {
    id: "turnaround-tag",
    title: "Turnaround Tag",
    difficulty: "Hard",
    bars: 2,
    memo: "End a loop with a compact blues tag",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 2, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 6, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 8, duration: "quarter", notes: [{ string: 4, fret: "7" }] },
      { step: 16, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 18, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 20, duration: "eighth", notes: [{ string: 5, fret: "5" }] },
      { step: 22, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 24, duration: "quarter", notes: [{ string: 6, fret: "5" }] },
    ],
  },
  {
    id: "triplet-feel",
    title: "Triplet Feel",
    difficulty: "Hard",
    bars: 1,
    memo: "Dense line for shuffle-style control",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "sixteenth", notes: [{ string: 5, fret: "5" }] },
      { step: 1, duration: "sixteenth", notes: [{ string: 5, fret: "7" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 4, fret: "5" }] },
      { step: 4, duration: "sixteenth", notes: [{ string: 4, fret: "7" }] },
      { step: 6, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 8, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 9, duration: "sixteenth", notes: [{ string: 2, fret: "5" }] },
      { step: 11, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
    ],
  },
  {
    id: "string-skip-run",
    title: "String Skip Run",
    difficulty: "Hard",
    bars: 2,
    memo: "Skip strings while staying inside the box",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 4, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 6, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 10, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 12, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 14, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 20, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 22, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 24, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 28, duration: "quarter", notes: [{ string: 5, fret: "5" }] },
    ],
  },
  {
    id: "chromatic-approach",
    title: "Chromatic Approach",
    difficulty: "Hard",
    bars: 1,
    memo: "Approach chord tones from a half step below",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "sixteenth", notes: [{ string: 4, fret: "6" }] },
      { step: 1, duration: "sixteenth", notes: [{ string: 4, fret: "7" }] },
      { step: 4, duration: "sixteenth", notes: [{ string: 3, fret: "4" }] },
      { step: 5, duration: "sixteenth", notes: [{ string: 3, fret: "5" }] },
      { step: 8, duration: "sixteenth", notes: [{ string: 2, fret: "7" }] },
      { step: 9, duration: "sixteenth", notes: [{ string: 2, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
    ],
  },
  {
    id: "position-shift-climb",
    title: "Position Shift Climb",
    difficulty: "Hard",
    bars: 2,
    memo: "Move from fifth to eighth position cleanly",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 4, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 6, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 10, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 16, duration: "eighth", notes: [{ string: 2, fret: "10" }] },
      { step: 18, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 20, duration: "eighth", notes: [{ string: 1, fret: "10" }] },
      { step: 24, duration: "eighth", notes: [{ string: 2, fret: "10" }] },
      { step: 28, duration: "quarter", notes: [{ string: 3, fret: "9" }] },
    ],
  },
  {
    id: "pedal-tone-sequence",
    title: "Pedal Tone Sequence",
    difficulty: "Hard",
    bars: 2,
    memo: "Return to a high pedal note between moving notes",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "sixteenth", notes: [{ string: 1, fret: "8" }] },
      { step: 1, duration: "sixteenth", notes: [{ string: 2, fret: "5" }] },
      { step: 2, duration: "sixteenth", notes: [{ string: 1, fret: "8" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 2, fret: "8" }] },
      { step: 4, duration: "sixteenth", notes: [{ string: 1, fret: "8" }] },
      { step: 5, duration: "sixteenth", notes: [{ string: 3, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 10, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 16, duration: "sixteenth", notes: [{ string: 1, fret: "8" }] },
      { step: 17, duration: "sixteenth", notes: [{ string: 4, fret: "5" }] },
      { step: 20, duration: "sixteenth", notes: [{ string: 1, fret: "8" }] },
      { step: 21, duration: "sixteenth", notes: [{ string: 4, fret: "7" }] },
      { step: 24, duration: "quarter", notes: [{ string: 2, fret: "8" }] },
    ],
  },
  {
    id: "wide-interval-lick",
    title: "Wide Interval Lick",
    difficulty: "Hard",
    bars: 1,
    memo: "Jump across strings while keeping time locked",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 6, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 8, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 10, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 3, fret: "5" }] },
    ],
  },
  {
    id: "sixteenth-burst",
    title: "Sixteenth Burst",
    difficulty: "Hard",
    bars: 1,
    memo: "Short speed burst into a held target note",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "sixteenth", notes: [{ string: 5, fret: "5" }] },
      { step: 1, duration: "sixteenth", notes: [{ string: 5, fret: "7" }] },
      { step: 2, duration: "sixteenth", notes: [{ string: 4, fret: "5" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 4, fret: "7" }] },
      { step: 4, duration: "sixteenth", notes: [{ string: 3, fret: "5" }] },
      { step: 5, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 6, duration: "sixteenth", notes: [{ string: 2, fret: "5" }] },
      { step: 8, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 2, fret: "8" }] },
    ],
  },
  {
    id: "descending-groups",
    title: "Descending Groups",
    difficulty: "Hard",
    bars: 2,
    memo: "Three-note descending cells across two bars",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "sixteenth", notes: [{ string: 1, fret: "8" }] },
      { step: 1, duration: "sixteenth", notes: [{ string: 1, fret: "5" }] },
      { step: 2, duration: "sixteenth", notes: [{ string: 2, fret: "8" }] },
      { step: 4, duration: "sixteenth", notes: [{ string: 1, fret: "5" }] },
      { step: 5, duration: "sixteenth", notes: [{ string: 2, fret: "8" }] },
      { step: 6, duration: "sixteenth", notes: [{ string: 2, fret: "5" }] },
      { step: 8, duration: "sixteenth", notes: [{ string: 2, fret: "8" }] },
      { step: 9, duration: "sixteenth", notes: [{ string: 2, fret: "5" }] },
      { step: 10, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 16, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 17, duration: "sixteenth", notes: [{ string: 3, fret: "5" }] },
      { step: 18, duration: "sixteenth", notes: [{ string: 4, fret: "7" }] },
      { step: 24, duration: "quarter", notes: [{ string: 5, fret: "5" }] },
    ],
  },
  {
    id: "sequence-builder",
    title: "Sequence Builder",
    difficulty: "Medium",
    bars: 2,
    memo: "Repeat a small cell from multiple scale tones",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 5, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 4, duration: "eighth", notes: [{ string: 4, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 10, duration: "eighth", notes: [{ string: 4, fret: "5" }] },
      { step: 12, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 16, duration: "eighth", notes: [{ string: 4, fret: "5" }] },
      { step: 18, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 20, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 24, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 26, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 28, duration: "quarter", notes: [{ string: 3, fret: "7" }] },
    ],
  },
  {
    id: "upper-box-targets",
    title: "Upper Box Targets",
    difficulty: "Medium",
    bars: 1,
    memo: "Resolve short upper-string phrases to strong targets",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 2, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 8, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 10, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 3, fret: "7" }] },
    ],
  },
  {
    id: "outside-note-push",
    title: "Outside Note Push",
    difficulty: "Hard",
    bars: 1,
    memo: "Use a passing note before resolving inside the box",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 2, duration: "sixteenth", notes: [{ string: 3, fret: "6" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 6, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 8, duration: "sixteenth", notes: [{ string: 2, fret: "6" }] },
      { step: 9, duration: "sixteenth", notes: [{ string: 2, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
    ],
  },
  {
    id: "endurance-loop",
    title: "Endurance Loop",
    difficulty: "Hard",
    bars: 2,
    memo: "Longer repeated pattern for alternate picking stamina",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "sixteenth", notes: [{ string: 5, fret: "5" }] },
      { step: 1, duration: "sixteenth", notes: [{ string: 5, fret: "7" }] },
      { step: 2, duration: "sixteenth", notes: [{ string: 4, fret: "5" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 4, fret: "7" }] },
      { step: 4, duration: "sixteenth", notes: [{ string: 5, fret: "5" }] },
      { step: 5, duration: "sixteenth", notes: [{ string: 5, fret: "7" }] },
      { step: 6, duration: "sixteenth", notes: [{ string: 4, fret: "5" }] },
      { step: 7, duration: "sixteenth", notes: [{ string: 4, fret: "7" }] },
      { step: 16, duration: "sixteenth", notes: [{ string: 3, fret: "5" }] },
      { step: 17, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 18, duration: "sixteenth", notes: [{ string: 2, fret: "5" }] },
      { step: 19, duration: "sixteenth", notes: [{ string: 2, fret: "8" }] },
      { step: 20, duration: "sixteenth", notes: [{ string: 3, fret: "5" }] },
      { step: 21, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 22, duration: "sixteenth", notes: [{ string: 2, fret: "5" }] },
      { step: 24, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
    ],
  },
  {
    id: "one-string-hook",
    title: "One String Hook",
    difficulty: "Easy",
    bars: 1,
    memo: "Melodic hook on one string for timing focus",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 4, duration: "quarter", notes: [{ string: 3, fret: "9" }] },
      { step: 8, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 10, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 3, fret: "7" }] },
    ],
  },
  {
    id: "root-fifth-pulse",
    title: "Root Fifth Pulse",
    difficulty: "Easy",
    bars: 1,
    memo: "Simple root and fifth groove for steady picking",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "quarter", notes: [{ string: 6, fret: "5" }] },
      { step: 4, duration: "quarter", notes: [{ string: 5, fret: "7" }] },
      { step: 8, duration: "quarter", notes: [{ string: 4, fret: "7" }] },
      { step: 12, duration: "quarter", notes: [{ string: 5, fret: "7" }] },
    ],
  },
  {
    id: "two-note-answer",
    title: "Two Note Answer",
    difficulty: "Easy",
    bars: 1,
    memo: "Short call-and-answer idea with space",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 2, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 10, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
    ],
  },
  {
    id: "low-high-question",
    title: "Low High Question",
    difficulty: "Easy",
    bars: 2,
    memo: "Answer a low-register idea with a high-register target",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 4, duration: "quarter", notes: [{ string: 4, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 5, fret: "5" }] },
      { step: 16, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 18, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 20, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
      { step: 28, duration: "quarter", notes: [{ string: 2, fret: "8" }] },
    ],
  },
  {
    id: "funk-pop",
    title: "Funk Pop",
    difficulty: "Medium",
    bars: 1,
    memo: "Short off-beat stabs for clean muting",
    totalSteps: 16,
    tabEvents: [
      { step: 1, duration: "sixteenth", notes: [{ string: 3, fret: "5" }, { string: 2, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 3, fret: "7" }, { string: 2, fret: "8" }] },
      { step: 7, duration: "sixteenth", notes: [{ string: 2, fret: "5" }, { string: 1, fret: "5" }] },
      { step: 10, duration: "eighth", notes: [{ string: 3, fret: "5" }, { string: 2, fret: "5" }] },
      { step: 14, duration: "eighth", notes: [{ string: 2, fret: "8" }, { string: 1, fret: "8" }] },
    ],
  },
  {
    id: "soul-sixths",
    title: "Soul Sixths",
    difficulty: "Medium",
    bars: 2,
    memo: "Two-note sixth shapes for melodic rhythm playing",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "quarter", notes: [{ string: 3, fret: "5" }, { string: 1, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 3, fret: "7" }, { string: 1, fret: "8" }] },
      { step: 8, duration: "quarter", notes: [{ string: 4, fret: "7" }, { string: 2, fret: "8" }] },
      { step: 16, duration: "quarter", notes: [{ string: 3, fret: "5" }, { string: 1, fret: "5" }] },
      { step: 22, duration: "eighth", notes: [{ string: 3, fret: "7" }, { string: 1, fret: "8" }] },
      { step: 24, duration: "quarter", notes: [{ string: 2, fret: "5" }, { string: 1, fret: "5" }] },
      { step: 28, duration: "quarter", notes: [{ string: 2, fret: "8" }, { string: 1, fret: "8" }] },
    ],
  },
  {
    id: "country-box",
    title: "Country Box",
    difficulty: "Medium",
    bars: 1,
    memo: "Pentatonic skips with a brighter country-style contour",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 3, fret: "6" }] },
      { step: 2, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 8, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 10, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 3, fret: "6" }] },
    ],
  },
  {
    id: "reggae-skank",
    title: "Reggae Skank",
    difficulty: "Medium",
    bars: 1,
    memo: "Backbeat chord stabs with full-beat rests",
    totalSteps: 16,
    tabEvents: [
      { step: 4, duration: "eighth", notes: [{ string: 3, fret: "5" }, { string: 2, fret: "5" }, { string: 1, fret: "5" }] },
      { step: 12, duration: "eighth", notes: [{ string: 3, fret: "5" }, { string: 2, fret: "5" }, { string: 1, fret: "5" }] },
    ],
  },
  {
    id: "minor-third-lift",
    title: "Minor Third Lift",
    difficulty: "Medium",
    bars: 2,
    memo: "Lift a repeated motif through the upper strings",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 4, duration: "quarter", notes: [{ string: 2, fret: "8" }] },
      { step: 8, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 10, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 1, fret: "8" }] },
      { step: 20, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 22, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 24, duration: "quarter", notes: [{ string: 1, fret: "8" }] },
      { step: 28, duration: "quarter", notes: [{ string: 2, fret: "5" }] },
    ],
  },
  {
    id: "walking-box",
    title: "Walking Box",
    difficulty: "Medium",
    bars: 2,
    memo: "Bass-like line that outlines the box across two bars",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 6, fret: "8" }] },
      { step: 4, duration: "eighth", notes: [{ string: 5, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 8, duration: "eighth", notes: [{ string: 4, fret: "5" }] },
      { step: 10, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 12, duration: "quarter", notes: [{ string: 5, fret: "7" }] },
      { step: 16, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 18, duration: "eighth", notes: [{ string: 4, fret: "5" }] },
      { step: 20, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 22, duration: "eighth", notes: [{ string: 5, fret: "5" }] },
      { step: 24, duration: "eighth", notes: [{ string: 6, fret: "8" }] },
      { step: 28, duration: "quarter", notes: [{ string: 6, fret: "5" }] },
    ],
  },
  {
    id: "arpeggio-outline",
    title: "Arpeggio Outline",
    difficulty: "Medium",
    bars: 1,
    memo: "Chord-tone outline inside a pentatonic-friendly position",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 2, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 4, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 10, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 3, fret: "5" }] },
    ],
  },
  {
    id: "metal-chug-answer",
    title: "Metal Chug Answer",
    difficulty: "Medium",
    bars: 2,
    memo: "Low-string pedal rhythm with a short high answer",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 8, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 10, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 4, fret: "7" }] },
      { step: 20, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 22, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 24, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
      { step: 28, duration: "quarter", notes: [{ string: 2, fret: "8" }] },
    ],
  },
  {
    id: "latin-syncopation",
    title: "Latin Syncopation",
    difficulty: "Hard",
    bars: 2,
    memo: "Tresillo-like accents for off-beat control",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 3, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 10, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 14, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 16, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 19, duration: "sixteenth", notes: [{ string: 3, fret: "5" }] },
      { step: 22, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 26, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 30, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
    ],
  },
  {
    id: "jazz-enclosure",
    title: "Jazz Enclosure",
    difficulty: "Hard",
    bars: 1,
    memo: "Chromatic enclosure around strong target notes",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "sixteenth", notes: [{ string: 3, fret: "6" }] },
      { step: 1, duration: "sixteenth", notes: [{ string: 3, fret: "4" }] },
      { step: 2, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 6, duration: "sixteenth", notes: [{ string: 2, fret: "7" }] },
      { step: 7, duration: "sixteenth", notes: [{ string: 2, fret: "6" }] },
      { step: 8, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
    ],
  },
  {
    id: "string-crossing-sprint",
    title: "String Crossing Sprint",
    difficulty: "Hard",
    bars: 2,
    memo: "Fast alternate-picking pattern across adjacent strings",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "sixteenth", notes: [{ string: 5, fret: "5" }] },
      { step: 1, duration: "sixteenth", notes: [{ string: 4, fret: "5" }] },
      { step: 2, duration: "sixteenth", notes: [{ string: 5, fret: "7" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 4, fret: "7" }] },
      { step: 4, duration: "sixteenth", notes: [{ string: 4, fret: "5" }] },
      { step: 5, duration: "sixteenth", notes: [{ string: 3, fret: "5" }] },
      { step: 6, duration: "sixteenth", notes: [{ string: 4, fret: "7" }] },
      { step: 7, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 16, duration: "sixteenth", notes: [{ string: 3, fret: "5" }] },
      { step: 17, duration: "sixteenth", notes: [{ string: 2, fret: "5" }] },
      { step: 18, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 19, duration: "sixteenth", notes: [{ string: 2, fret: "8" }] },
      { step: 20, duration: "sixteenth", notes: [{ string: 2, fret: "5" }] },
      { step: 21, duration: "sixteenth", notes: [{ string: 1, fret: "5" }] },
      { step: 22, duration: "sixteenth", notes: [{ string: 2, fret: "8" }] },
      { step: 24, duration: "quarter", notes: [{ string: 1, fret: "8" }] },
    ],
  },
  {
    id: "outside-resolution",
    title: "Outside Resolution",
    difficulty: "Hard",
    bars: 2,
    memo: "Step outside briefly, then resolve to stable chord tones",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 2, duration: "sixteenth", notes: [{ string: 3, fret: "6" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 6, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 8, duration: "sixteenth", notes: [{ string: 2, fret: "6" }] },
      { step: 9, duration: "sixteenth", notes: [{ string: 2, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
      { step: 20, duration: "sixteenth", notes: [{ string: 1, fret: "6" }] },
      { step: 21, duration: "sixteenth", notes: [{ string: 1, fret: "8" }] },
      { step: 24, duration: "quarter", notes: [{ string: 2, fret: "8" }] },
      { step: 28, duration: "quarter", notes: [{ string: 3, fret: "5" }] },
    ],
  },
  {
    id: "wide-stretch-map",
    title: "Wide Stretch Map",
    difficulty: "Hard",
    bars: 2,
    memo: "Large fretboard jumps for position awareness",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 2, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 4, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 3, fret: "7" }] },
      { step: 16, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 18, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 20, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 24, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 28, duration: "quarter", notes: [{ string: 4, fret: "7" }] },
    ],
  },
  {
    id: "arena-rock-call",
    title: "Arena Rock Call",
    difficulty: "Easy",
    bars: 1,
    memo: "Open, vocal-style rock hook with a strong final target",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "quarter", notes: [{ string: 3, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 8, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 2, fret: "8" }] },
    ],
  },
  {
    id: "power-chord-walk",
    title: "Power Chord Walk",
    difficulty: "Easy",
    bars: 2,
    memo: "Classic low-string power-chord movement",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "quarter", notes: [{ string: 6, fret: "5" }, { string: 5, fret: "7" }] },
      { step: 4, duration: "quarter", notes: [{ string: 6, fret: "8" }, { string: 5, fret: "10" }] },
      { step: 8, duration: "quarter", notes: [{ string: 5, fret: "5" }, { string: 4, fret: "7" }] },
      { step: 12, duration: "quarter", notes: [{ string: 5, fret: "7" }, { string: 4, fret: "9" }] },
      { step: 16, duration: "quarter", notes: [{ string: 6, fret: "5" }, { string: 5, fret: "7" }] },
      { step: 20, duration: "quarter", notes: [{ string: 6, fret: "3" }, { string: 5, fret: "5" }] },
      { step: 24, duration: "quarter", notes: [{ string: 5, fret: "5" }, { string: 4, fret: "7" }] },
      { step: 28, duration: "quarter", notes: [{ string: 6, fret: "5" }, { string: 5, fret: "7" }] },
    ],
  },
  {
    id: "blues-rock-snap",
    title: "Blues Rock Snap",
    difficulty: "Medium",
    bars: 1,
    memo: "Punchy minor-box phrase with a classic rock cadence",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 2, duration: "sixteenth", notes: [{ string: 2, fret: "5" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 4, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 6, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 10, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 3, fret: "7" }] },
    ],
  },
  {
    id: "open-road-double-stops",
    title: "Open Road Double Stops",
    difficulty: "Medium",
    bars: 2,
    memo: "Wide, ringing two-note shapes for old-school rock phrasing",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "quarter", notes: [{ string: 2, fret: "5" }, { string: 1, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 2, fret: "8" }, { string: 1, fret: "8" }] },
      { step: 6, duration: "eighth", notes: [{ string: 2, fret: "5" }, { string: 1, fret: "5" }] },
      { step: 8, duration: "quarter", notes: [{ string: 3, fret: "7" }, { string: 2, fret: "8" }] },
      { step: 16, duration: "quarter", notes: [{ string: 3, fret: "5" }, { string: 2, fret: "5" }] },
      { step: 20, duration: "eighth", notes: [{ string: 3, fret: "7" }, { string: 2, fret: "8" }] },
      { step: 22, duration: "eighth", notes: [{ string: 2, fret: "5" }, { string: 1, fret: "5" }] },
      { step: 24, duration: "quarter", notes: [{ string: 2, fret: "8" }, { string: 1, fret: "8" }] },
      { step: 28, duration: "quarter", notes: [{ string: 2, fret: "5" }, { string: 1, fret: "5" }] },
    ],
  },
  {
    id: "heavy-pedal-riff",
    title: "Heavy Pedal Riff",
    difficulty: "Medium",
    bars: 2,
    memo: "Low A pedal riff with hard-rock accents",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 2, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 6, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 6, fret: "8" }] },
      { step: 10, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 5, fret: "5" }] },
      { step: 16, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 18, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 19, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 20, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 22, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 24, duration: "eighth", notes: [{ string: 5, fret: "5" }] },
      { step: 28, duration: "quarter", notes: [{ string: 6, fret: "5" }] },
    ],
  },
  {
    id: "sunset-lead-line",
    title: "Sunset Lead Line",
    difficulty: "Medium",
    bars: 2,
    memo: "Singing hard-rock lead line without bends",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 2, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 4, duration: "quarter", notes: [{ string: 1, fret: "8" }] },
      { step: 8, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 10, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 2, fret: "5" }] },
      { step: 16, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 18, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 20, duration: "quarter", notes: [{ string: 2, fret: "8" }] },
      { step: 24, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 28, duration: "quarter", notes: [{ string: 1, fret: "8" }] },
    ],
  },
  {
    id: "stomp-rock-octaves",
    title: "Stomp Rock Octaves",
    difficulty: "Medium",
    bars: 2,
    memo: "Octave jumps with a stomping rock feel",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "quarter", notes: [{ string: 6, fret: "5" }, { string: 4, fret: "7" }] },
      { step: 4, duration: "eighth", notes: [{ string: 6, fret: "5" }, { string: 4, fret: "7" }] },
      { step: 6, duration: "eighth", notes: [{ string: 6, fret: "8" }, { string: 4, fret: "10" }] },
      { step: 8, duration: "quarter", notes: [{ string: 5, fret: "5" }, { string: 3, fret: "7" }] },
      { step: 12, duration: "quarter", notes: [{ string: 6, fret: "5" }, { string: 4, fret: "7" }] },
      { step: 16, duration: "quarter", notes: [{ string: 5, fret: "7" }, { string: 3, fret: "9" }] },
      { step: 20, duration: "eighth", notes: [{ string: 5, fret: "5" }, { string: 3, fret: "7" }] },
      { step: 22, duration: "eighth", notes: [{ string: 6, fret: "8" }, { string: 4, fret: "10" }] },
      { step: 24, duration: "quarter", notes: [{ string: 6, fret: "5" }, { string: 4, fret: "7" }] },
    ],
  },
  {
    id: "classic-rock-climb",
    title: "Classic Rock Climb",
    difficulty: "Hard",
    bars: 2,
    memo: "Ascending box run that resolves like a vintage rock solo tag",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "sixteenth", notes: [{ string: 5, fret: "5" }] },
      { step: 1, duration: "sixteenth", notes: [{ string: 5, fret: "7" }] },
      { step: 2, duration: "sixteenth", notes: [{ string: 4, fret: "5" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 4, fret: "7" }] },
      { step: 4, duration: "sixteenth", notes: [{ string: 3, fret: "5" }] },
      { step: 5, duration: "sixteenth", notes: [{ string: 3, fret: "7" }] },
      { step: 6, duration: "sixteenth", notes: [{ string: 2, fret: "5" }] },
      { step: 7, duration: "sixteenth", notes: [{ string: 2, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
      { step: 16, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 18, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 20, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 24, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
      { step: 28, duration: "quarter", notes: [{ string: 2, fret: "8" }] },
    ],
  },
  {
    id: "gallop-engine",
    title: "Gallop Engine",
    difficulty: "Hard",
    bars: 2,
    memo: "Driving hard-rock gallop pattern for tight right-hand control",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 1, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 4, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 5, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 7, duration: "sixteenth", notes: [{ string: 5, fret: "7" }] },
      { step: 8, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 9, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 11, duration: "sixteenth", notes: [{ string: 6, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 5, fret: "5" }] },
      { step: 16, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 17, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 19, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 20, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 21, duration: "sixteenth", notes: [{ string: 5, fret: "7" }] },
      { step: 23, duration: "sixteenth", notes: [{ string: 4, fret: "7" }] },
      { step: 24, duration: "quarter", notes: [{ string: 6, fret: "5" }] },
    ],
  },
  {
    id: "riff-tag-turnaround",
    title: "Riff Tag Turnaround",
    difficulty: "Hard",
    bars: 2,
    memo: "Tough low-string riff that snaps back to the root",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 2, duration: "sixteenth", notes: [{ string: 6, fret: "5" }] },
      { step: 3, duration: "sixteenth", notes: [{ string: 5, fret: "7" }] },
      { step: 4, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 6, duration: "eighth", notes: [{ string: 5, fret: "5" }] },
      { step: 8, duration: "sixteenth", notes: [{ string: 6, fret: "8" }] },
      { step: 9, duration: "sixteenth", notes: [{ string: 6, fret: "7" }] },
      { step: 10, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 5, fret: "7" }] },
      { step: 16, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 18, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 20, duration: "eighth", notes: [{ string: 4, fret: "5" }] },
      { step: 22, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 24, duration: "quarter", notes: [{ string: 5, fret: "5" }] },
      { step: 28, duration: "quarter", notes: [{ string: 6, fret: "5" }] },
    ],
  },
  {
    id: "hard-rock-answer",
    title: "Hard Rock Answer",
    difficulty: "Hard",
    bars: 2,
    memo: "High-register answer phrase with aggressive rhythmic gaps",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 2, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 7, duration: "sixteenth", notes: [{ string: 1, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 3, fret: "7" }] },
      { step: 16, duration: "sixteenth", notes: [{ string: 2, fret: "5" }] },
      { step: 17, duration: "sixteenth", notes: [{ string: 2, fret: "8" }] },
      { step: 18, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 22, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 24, duration: "quarter", notes: [{ string: 2, fret: "8" }] },
      { step: 28, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
    ],
  },
  {
    id: "proto-metal-descent",
    title: "Proto Metal Descent",
    difficulty: "Hard",
    bars: 2,
    memo: "Dark descending line with low-string weight",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 1, fret: "8" }] },
      { step: 2, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 6, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 10, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 4, fret: "7" }] },
      { step: 16, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 18, duration: "eighth", notes: [{ string: 6, fret: "8" }] },
      { step: 20, duration: "eighth", notes: [{ string: 6, fret: "7" }] },
      { step: 22, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 24, duration: "quarter", notes: [{ string: 5, fret: "7" }] },
      { step: 28, duration: "quarter", notes: [{ string: 6, fret: "5" }] },
    ],
  },
  {
    id: "late-night-power-ballad",
    title: "Late Night Power Ballad",
    difficulty: "Medium",
    bars: 2,
    memo: "Slow, dramatic double-stop melody for big-rock phrasing",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "quarter", notes: [{ string: 2, fret: "5" }, { string: 1, fret: "5" }] },
      { step: 4, duration: "quarter", notes: [{ string: 2, fret: "8" }, { string: 1, fret: "8" }] },
      { step: 8, duration: "quarter", notes: [{ string: 3, fret: "7" }, { string: 2, fret: "8" }] },
      { step: 12, duration: "quarter", notes: [{ string: 2, fret: "5" }, { string: 1, fret: "5" }] },
      { step: 16, duration: "quarter", notes: [{ string: 3, fret: "5" }, { string: 2, fret: "5" }] },
      { step: 20, duration: "quarter", notes: [{ string: 3, fret: "7" }, { string: 2, fret: "8" }] },
      { step: 24, duration: "quarter", notes: [{ string: 2, fret: "8" }, { string: 1, fret: "8" }] },
      { step: 28, duration: "quarter", notes: [{ string: 2, fret: "5" }, { string: 1, fret: "5" }] },
    ],
  },
  {
    id: "hammer-box-hook",
    title: "Hammer Box Hook",
    difficulty: "Medium",
    bars: 1,
    memo: "Hard-rock box phrase built around hammer-ons",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 3, fret: "5" }], technique: { type: "hammer-on", toFret: "7" } },
      { step: 2, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 2, fret: "5" }], technique: { type: "hammer-on", toFret: "8" } },
      { step: 6, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 10, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 3, fret: "7" }] },
    ],
  },
  {
    id: "pull-off-return",
    title: "Pull Off Return",
    difficulty: "Medium",
    bars: 1,
    memo: "Descending rock phrase with pull-off returns",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 1, fret: "8" }], technique: { type: "pull-off", toFret: "5" } },
      { step: 2, duration: "eighth", notes: [{ string: 2, fret: "8" }], technique: { type: "pull-off", toFret: "5" } },
      { step: 4, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 6, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 4, fret: "7" }] },
      { step: 10, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 12, duration: "quarter", notes: [{ string: 6, fret: "5" }] },
    ],
  },
  {
    id: "slide-to-fire",
    title: "Slide To Fire",
    difficulty: "Medium",
    bars: 2,
    memo: "Slide into strong targets for vintage lead phrasing",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "quarter", notes: [{ string: 4, fret: "5" }], technique: { type: "slide", toFret: "7" } },
      { step: 4, duration: "eighth", notes: [{ string: 3, fret: "5" }] },
      { step: 6, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 8, duration: "quarter", notes: [{ string: 2, fret: "5" }], technique: { type: "slide", toFret: "8" } },
      { step: 16, duration: "eighth", notes: [{ string: 2, fret: "8" }] },
      { step: 18, duration: "eighth", notes: [{ string: 1, fret: "5" }] },
      { step: 20, duration: "quarter", notes: [{ string: 1, fret: "5" }], technique: { type: "slide", toFret: "8" } },
      { step: 28, duration: "quarter", notes: [{ string: 2, fret: "8" }] },
    ],
  },
  {
    id: "legato-rock-run",
    title: "Legato Rock Run",
    difficulty: "Hard",
    bars: 2,
    memo: "Fast hammer-on and pull-off line for fluid rock leads",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "sixteenth", notes: [{ string: 5, fret: "5" }], technique: { type: "hammer-on", toFret: "7" } },
      { step: 2, duration: "sixteenth", notes: [{ string: 4, fret: "5" }], technique: { type: "hammer-on", toFret: "7" } },
      { step: 4, duration: "sixteenth", notes: [{ string: 3, fret: "5" }], technique: { type: "hammer-on", toFret: "7" } },
      { step: 6, duration: "eighth", notes: [{ string: 2, fret: "5" }], technique: { type: "hammer-on", toFret: "8" } },
      { step: 10, duration: "eighth", notes: [{ string: 1, fret: "8" }], technique: { type: "pull-off", toFret: "5" } },
      { step: 12, duration: "quarter", notes: [{ string: 2, fret: "8" }] },
      { step: 16, duration: "sixteenth", notes: [{ string: 2, fret: "8" }], technique: { type: "pull-off", toFret: "5" } },
      { step: 18, duration: "sixteenth", notes: [{ string: 3, fret: "7" }], technique: { type: "pull-off", toFret: "5" } },
      { step: 20, duration: "sixteenth", notes: [{ string: 4, fret: "7" }], technique: { type: "pull-off", toFret: "5" } },
      { step: 24, duration: "quarter", notes: [{ string: 5, fret: "7" }] },
      { step: 28, duration: "quarter", notes: [{ string: 6, fret: "5" }] },
    ],
  },
  {
    id: "slide-riff-turn",
    title: "Slide Riff Turn",
    difficulty: "Hard",
    bars: 2,
    memo: "Low riff with slides and a hard-rock turnaround",
    totalSteps: 32,
    tabEvents: [
      { step: 0, duration: "eighth", notes: [{ string: 6, fret: "3" }], technique: { type: "slide", toFret: "5" } },
      { step: 2, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 4, duration: "eighth", notes: [{ string: 5, fret: "5" }], technique: { type: "slide", toFret: "7" } },
      { step: 6, duration: "eighth", notes: [{ string: 6, fret: "5" }] },
      { step: 8, duration: "eighth", notes: [{ string: 6, fret: "8" }], technique: { type: "pull-off", toFret: "5" } },
      { step: 12, duration: "quarter", notes: [{ string: 5, fret: "7" }] },
      { step: 16, duration: "eighth", notes: [{ string: 4, fret: "5" }], technique: { type: "hammer-on", toFret: "7" } },
      { step: 20, duration: "eighth", notes: [{ string: 5, fret: "7" }] },
      { step: 24, duration: "eighth", notes: [{ string: 6, fret: "8" }], technique: { type: "slide", toFret: "5" } },
      { step: 28, duration: "quarter", notes: [{ string: 6, fret: "5" }] },
    ],
  },
  {
    id: "hammer-pull-flash",
    title: "Hammer Pull Flash",
    difficulty: "Hard",
    bars: 1,
    memo: "Compact hammer-on and pull-off burst for solo endings",
    totalSteps: 16,
    tabEvents: [
      { step: 0, duration: "sixteenth", notes: [{ string: 2, fret: "5" }], technique: { type: "hammer-on", toFret: "8" } },
      { step: 2, duration: "sixteenth", notes: [{ string: 1, fret: "5" }], technique: { type: "hammer-on", toFret: "8" } },
      { step: 4, duration: "sixteenth", notes: [{ string: 1, fret: "8" }], technique: { type: "pull-off", toFret: "5" } },
      { step: 6, duration: "sixteenth", notes: [{ string: 2, fret: "8" }], technique: { type: "pull-off", toFret: "5" } },
      { step: 8, duration: "eighth", notes: [{ string: 3, fret: "7" }] },
      { step: 10, duration: "eighth", notes: [{ string: 2, fret: "5" }] },
      { step: 12, duration: "quarter", notes: [{ string: 1, fret: "5" }] },
    ],
  },
];
